package dev.opcode42.sdk

import dev.opcode42.sdk.apis.SessionApi
import okhttp3.Credentials
import okhttp3.Interceptor
import okhttp3.OkHttpClient
import okhttp3.Response
import java.net.URLEncoder

/**
 * Hand-written wrapper around the generated Opcode42/opencode REST SDK (package
 * `dev.opcode42.sdk.apis` / `dev.opcode42.sdk.models`, regenerated by
 * `scripts/gen-sdks.sh`).
 *
 * Codegen covers request/response types and request functions; the cross-cutting
 * concerns — Basic auth and `x-opencode-directory` routing — are injected here via
 * an OkHttp interceptor (plan 06 "Auth & Directory Header Injection"). Persistent
 * streaming (SSE `/event`, WebSocket `/pty/{id}/connect`) is NOT generated; the
 * Android app supplies those hand-written clients in its `core:network` /
 * `core:sdk` modules. This wrapper is the typed-REST seam consumers build on.
 *
 * Wire-generic: point [baseUrl] at a Opcode42 daemon or a real opencode daemon — the
 * contract is identical.
 *
 * Example:
 * ```
 * val opcode42 = Opcode42Client("http://localhost:4096", directory = "/work/proj")
 * val sessions = opcode42.sessions().sessionList()
 * ```
 */
class Opcode42Client(
    private val baseUrl: String,
    private val directory: String = "",
    username: String = "",
    password: String = "",
    baseClient: OkHttpClient = OkHttpClient(),
) {
    private val authHeader: String? =
        if (username.isNotEmpty()) Credentials.basic(username, password) else null

    /** OkHttp client with auth + directory-routing injection on every request. */
    val httpClient: OkHttpClient = baseClient.newBuilder()
        .addInterceptor(Opcode42HeaderInterceptor(authHeader, directory))
        .build()

    // The generated *Api classes are ApiClient subclasses constructed with
    // (basePath, client); we hand each our intercepted client at construction.

    /** Session CRUD, prompts, share, summarize, etc. */
    fun sessions(): SessionApi = SessionApi(baseUrl, httpClient)

    // Add further typed API accessors (ConfigApi, ProviderApi, …) here as
    // consumers need them; each is `XxxApi(baseUrl, httpClient)`.

    /** The base URL this client targets. */
    fun baseUrl(): String = baseUrl
}

/**
 * Injects `Authorization: Basic …` (when configured) and the
 * `X-Opencode-Directory` routing header (URL-encoded) into every request, per the
 * unified injection contract in plan 06.
 */
internal class Opcode42HeaderInterceptor(
    private val authHeader: String?,
    private val directory: String,
) : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
        val builder = chain.request().newBuilder()
        if (authHeader != null) {
            builder.header("Authorization", authHeader)
        }
        if (directory.isNotEmpty()) {
            // encodeURIComponent-equivalent: opencode decodes this header with JS
            // decodeURIComponent, so encode spaces as %20 (not '+').
            builder.header(
                "X-Opencode-Directory",
                URLEncoder.encode(directory, "UTF-8").replace("+", "%20"),
            )
        }
        return chain.proceed(builder.build())
    }
}
