#!/usr/bin/env bash
# Sync the frozen wire contract from the opencode reference checkout into the
# Opcode42 repo. This is the ONLY way the vendored reference should change — never
# edit conformance/openapi-reference.json by hand.
#
# Usage: scripts/sync-openapi.sh [path-to-opencode-checkout]
set -euo pipefail

OPENCODE_DIR="${1:-/Users/rotemmiz/git/opencode}"
SRC="$OPENCODE_DIR/packages/sdk/openapi.json"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$REPO_ROOT/conformance/openapi-reference.json"
PROV="$REPO_ROOT/conformance/openapi-reference.provenance.txt"

if [[ ! -f "$SRC" ]]; then
  echo "error: spec not found at $SRC" >&2
  exit 1
fi

mkdir -p "$(dirname "$DEST")"
cp "$SRC" "$DEST"

# Embeddable copy for the daemon's GET /doc (single-binary requirement). This is
# a derived copy of the canonical reference above; a guard test in
# internal/api/spec asserts the two stay byte-identical.
EMBED="$REPO_ROOT/internal/api/spec/openapi.json"
mkdir -p "$(dirname "$EMBED")"
cp "$SRC" "$EMBED"

sha256() { shasum -a 256 "$1" | awk '{print $1}'; }
src_sha="$(sha256 "$SRC")"
opencode_commit="$(git -C "$OPENCODE_DIR" rev-parse HEAD 2>/dev/null || echo 'unknown')"
paths="$(python3 -c "import json;print(len(json.load(open('$DEST'))['paths']))")"

cat > "$PROV" <<EOF
# Provenance of conformance/openapi-reference.json — generated by scripts/sync-openapi.sh.
# Do not edit either file by hand; re-run the script to update.
source:           $SRC
opencode_commit:  $opencode_commit
sha256:           $src_sha
openapi_paths:    $paths
synced_at:        $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo "vendored $paths paths -> $DEST"
echo "embed copy        -> $EMBED"
echo "provenance -> $PROV (opencode @ $opencode_commit)"
